### ISSUE TITLE
Add localization and translation system

### ISSUE THREAD

**Issue by Starciad** [Starciad/StardustSandbox#36]
Build the foundations of the localization system that will be used in the game. Its model will be similar to the following: there will be .ini files that will contain information for each of the languages ​​added to the game and these will be read and correctly processed in-game, which will allow their values ​​to be extracted and used during the game. No language content strings will be hardcoded.

**Comment by PiotrekUnityDeveloper** [comment]
great to see you resumed your work on this project 🤩

**Comment by Starciad** [comment]
> É ótimo ver que você retomou seu trabalho neste projeto 🤩

Yeah! Thankfully, I've reached a more relaxed and stable period, so I decided to dive back into this project and have some fun with it.

My goal now is to stay focused enough to release a playable version by the end of the year. If that doesn’t happen... well, there’s always time!

I'm really happy to see your excitement about the project—it truly motivates me to keep going. Thank you so much! 😊
